# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: Strohm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache things
        uses: actions/cache@v3
        env:
          cache-name: cache-m2
        with:
          path: |
            ~/.m2
            ~/.gradle/caches
            ~/.gradle/wrapper
            Strohm/.shadow-cljs
            Strohm/ios/Strohm/.build
          key: ${{ runner.os }}-v3-build-${{ env.cache-name }}-${{ hashFiles('Strohm/**/deps.edn', 'Strohm/**/build.gradle', 'Strohm/**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-v3-build-${{ env.cache-name }}-
            ${{ runner.os }}-v3-build-
            ${{ runner.os }}-v3-

      - name: Show java version
        run: java -version

      - name: Install prerequisites
        run: |
          brew install openjdk clojure/tools/clojure
          sudo ln -sfn $HOME/.homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
          echo "Java version is now:"
          java -version

      - name: Prepare
        run: yarn install --frozen-lockfile

      - name: Test ClojureScript
        run: yarn shadow-cljs compile :test

      - name: Release ClojureScript
        run: yarn shadow-cljs release :strohm-native

      - name: Test iOS
        run: |
          cd ios/StrohmNative
          swift package generate-xcodeproj
          xcodebuild -project StrohmNative.xcodeproj -scheme StrohmNative-Package -destination 'platform=iOS Simulator,name=iPhone 12'

      - name: Test Android
        run: |
          cd android
          ./gradlew clean test
